import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";
import Search from "~/components/Search";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col">
        <Search />
        {/* <div>
          {user.isSignedIn && <SignOutButton />}
          {!user.isSignedIn && <SignInButton />}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
      </main>
    </>
  );
};

export default Home;
