import { type NextPage } from "next";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { MultiUploader } from "~/components/admin/Uploader";

const Upload: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <MultiUploader />
      </main>
    </>
  );
};

export default Upload;
