export const ProductData = [
  {
    id: "1",
    name: "Floral Dress",
    imageUrl: "/assets/images/dresses/floral-dress.png",
    price: 300,
    category: "Dresses",
    isSale: true,
    salePrice: 200,
    quantity: 10,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "2",
    name: "Short Dress",
    imageUrl: "/assets/images/dresses/blue-short-sleeve-dress.png",
    price: 150,
    category: "Dresses",
    isSale: false,
    salePrice: 0,
    quantity: 5,
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "3",
    name: "Tube Dress",
    imageUrl: "/assets/images/dresses/tube-dress.png",
    price: 100,
    category: "Dresses",
    isSale: false,
    salePrice: 0,
    quantity: 5,
    sizes: ["XS"],
  },
  {
    id: "4",
    name: "Red Long Dress",
    imageUrl: "/assets/images/dresses/red-long-dress.png",
    price: 100,
    category: "Dresses",
    isSale: false,
    salePrice: 0,
    quantity: 5,
    sizes: ["XS", "S", "M"],
  },
  {
    id: "5",
    name: "Short Floral Dress",
    imageUrl: "/assets/images/dresses/short-floral-dress.png",
    price: 400,
    category: "Dresses",
    isSale: true,
    salePrice: 200,
    quantity: 5,
    sizes: ["XS", "S"],
  },
  {
    id: "6",
    name: "Tracksuit",
    imageUrl: "/assets/images/dresses/tracksuit.png",
    price: 250,
    category: "Dresses",
    isSale: false,
    salePrice: 0,
    quantity: 5,
    sizes: ["XS", "S", "M"],
  },
];
