export const ProductData = [
  {
    id: "1",
    name: "Floral Dress",
    imageUrl: "/assets/images/dresses/floral-dress.png",
    price: 300,
    category: "Dresses",
    sale: true,
    salePrice: 200,
  },
  {
    id: "2",
    name: "Short Dress",
    imageUrl: "/assets/images/dresses/blue-short-sleeve-dress.png",
    price: 150,
    category: "Dresses",
  },
  {
    id: "3",
    name: "Tube Dress",
    imageUrl: "/assets/images/dresses/tube-dress.png",
    price: 100,
    category: "Dresses",
  },
  {
    id: "4",
    name: "Red Long Dress",
    imageUrl: "/assets/images/dresses/red-long-dress.png",
    price: 100,
    category: "Dresses",
    sale: false,
  },
  {
    id: "5",
    name: "Short Floral Dress",
    imageUrl: "/assets/images/dresses/short-floral-dress.png",
    price: 400,
    category: "Dresses",
    sale: true,
    salePrice: 200,
  },
  {
    id: "6",
    name: "Tracksuit",
    imageUrl: "/assets/images/dresses/tracksuit.png",
    price: 250,
    category: "Dresses",
    sale: false,
  },
];
