import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  Squares2X2Icon,
  ArchiveBoxIcon,
  BookmarkIcon,
} from "@heroicons/react/24/outline";

import { motion } from "framer-motion";
import SideNav from "~/components/admin/SideNav";
import AdminNav from "~/components/admin/AdminNav";

const Admin: NextPage = () => {
  // const user = useUser();
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const user = useUser();

  const MenuVariant = {
    hidden: { width: 0 },
    visible: {
      width: 300,
    },
  };

  const listItemVariant = {};

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminNav />
      <main className="flex min-h-screen w-full">
        <SideNav />
        <div className=" w-full bg-gray-50 px-6 py-10 lg:w-[calc(100%-300px)] lg:px-10">
          <div className="flex w-full">
            <form className="w-full">
              <input
                type="text"
                className="w-full rounded-lg border border-gray-200 bg-inherit px-4 py-2 focus:border focus:border-gray-300 focus:outline-none focus:ring-0"
                placeholder="Search..."
              />
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Admin;
